In [ ]:
demo_order = {
    "order_id": 10001,
    "customer": {
        "user_id": 1,
        "email": "alice@example.com",
    },
    "items": [
        {
            "sku": "ESS-001",
            "quantity": 2,
            "price": "129.99",
        }
    ],
}

In [2]:
import json

In [3]:
# json.dumps()

json_string = json.dumps(
    demo_order,
    ensure_ascii=False,
    indent=2
)

In [4]:
print(json_string)

{
  "order_id": 10001,
  "customer": {
    "user_id": 1,
    "email": "alice@example.com"
  },
  "items": [
    {
      "sku": "ESS-001",
      "quantity": 2,
      "price": "129.99"
    }
  ]
}

In [5]:
print(type(json_string))

<class 'str'>

In [6]:
#json.loads()
parsed_order = json.loads(json_string)

In [7]:
parsed_order

{'order_id': 10001,
 'customer': {'user_id': 1, 'email': 'alice@example.com'},
 'items': [{'sku': 'ESS-001', 'quantity': 2, 'price': '129.99'}]}

In [8]:
parsed_order["customer"]["email"]

'alice@example.com'

In [14]:
#json.dump() 
from pathlib import Path
with (Path("data/demo_order.json")).open("w", encoding = "utf-8") as f:
    json.dump(
        demo_order,
        f,
        ensure_ascii=False,
        indent=2,
    )

In [17]:
#json.load()

with (Path("data/demo_order.json")).open("r", encoding = "utf-8") as f:
    loaded_order = json.load(f)

In [18]:
loaded_order

{'order_id': 10001,
 'customer': {'user_id': 1, 'email': 'alice@example.com'},
 'items': [{'sku': 'ESS-001', 'quantity': 2, 'price': '129.99'}]}

In [19]:
import csv

In [20]:
# csv.DictWriter

In [25]:
# csv.DictReader
with (Path("data/customers.csv")).open("r", encoding = "utf-8") as f:
    reader = csv.DictReader(f)
    rows = list(reader)

In [24]:
print(reader)

<csv.DictReader object at 0x7a1255ee7e30>

In [27]:
rows[:1]

[{'user_id': '1',
  'email': 'alice@example.com',
  'country': 'US',
  'segment': 'Premium',
  'status': 'ACTIVE'}]

In [28]:
clean_customer_rows = []

In [31]:
with (Path("data/customers.csv")).open("r", encoding = "utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        clean_customer_rows.append(
            {
                "user_id": int(row["user_id"]),
                "email": row["email"],
                "country": row["country"],
                "segment": row["segment"].lower(),
                "status": row["status"].lower()
            }
        )

In [32]:
clean_customer_rows

[{'user_id': 1,
  'email': 'alice@example.com',
  'country': 'US',
  'segment': 'premium',
  'status': 'active'},
 {'user_id': 2,
  'email': 'bob@example.com',
  'country': 'US',
  'segment': 'new',
  'status': 'active'},
 {'user_id': 3,
  'email': 'carlos@example.com',
  'country': 'MX',
  'segment': 'regular',
  'status': 'active'}]

In [34]:
import pandas as pd

In [35]:
#pd.read_csv
customer_df = pd.read_csv(Path("data/customers.csv"))

In [36]:
customer_df

   user_id               email country  segment  status
0        1   alice@example.com      US  Premium  ACTIVE
1        2     bob@example.com      US      New  active
2        3  carlos@example.com      MX  Regular  ACTIVE

In [37]:
customer_df.head(1)

   user_id              email country  segment  status
0        1  alice@example.com      US  Premium  ACTIVE

In [38]:
customer_df.columns

Index(['user_id', 'email', 'country', 'segment', 'status'], dtype='str')

In [39]:
customer_df.dtypes

user_id    int64
email        str
country      str
segment      str
status       str
dtype: object

In [40]:
customer_df[["user_id", "email", "status"]]

   user_id               email  status
0        1   alice@example.com  ACTIVE
1        2     bob@example.com  active
2        3  carlos@example.com  ACTIVE

In [41]:
# df.assign
customers_normalized_df= customer_df.assign(
    segment=customer_df["segment"].str.lower(),
    status=customer_df["status"].str.lower(),
)

In [42]:
customers_normalized_df

   user_id               email country  segment  status
0        1   alice@example.com      US  premium  active
1        2     bob@example.com      US      new  active
2        3  carlos@example.com      MX  regular  active

In [45]:
# df.query
df1 = customers_normalized_df.query("segment == 'premium'")

In [46]:
df1

   user_id              email country  segment  status
0        1  alice@example.com      US  premium  active

In [48]:
# df.groupby
df2 = customers_normalized_df.groupby("country").agg(customers_count = ("user_id", "count"))

In [49]:
df2

         customers_count
country
MX                     1
US                     2

In [51]:
# df.itertuples
rows_for_db = []
for row in customers_normalized_df.itertuples(index=False):
    rows_for_db.append(
        (
        int(row.user_id),
        row.email,
        row.country,
        row.segment,
        row.status
        )
    )

In [52]:
rows_for_db

[(1, 'alice@example.com', 'US', 'premium', 'active'),
 (2, 'bob@example.com', 'US', 'new', 'active'),
 (3, 'carlos@example.com', 'MX', 'regular', 'active')]

In [55]:
pip install psycopg

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg
  Downloading psycopg-3.3.4-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: typing-extensions>=4.6 in /usr/local/lib/python3.12/site-packages (from psycopg) (4.15.0)
Downloading psycopg-3.3.4-py3-none-any.whl (213 kB)
Installing collected packages: psycopg
Successfully installed psycopg-3.3.4

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# psycopg.connect
# psycopg.execute
with psycopg.connect(host, user) as conn:
    with conn.cursor() as cur:
        cur.execute("SELECT 1")
        result = cur.fetchone
    conn.commit()

In [57]:
import os                                                                                                                                                                                                                                                                                                                                                                                                                         
PG_DSN = (                                                                                                                                                                                                             
 f"postgresql://{os.environ['POSTGRES_USER']}:{os.environ['POSTGRES_PASSWORD']}"                                                                                                    
 f"@{os.environ['POSTGRES_HOST']}:{os.environ['POSTGRES_PORT']}"                                                                                                                                                            
 f"/{os.environ['POSTGRES_DB']}"                                                                                                                                                                            
)

In [70]:
# psycopg.connect
# psycopg.execute
import psycopg2
with psycopg2.connect(PG_DSN) as conn:
     with conn.cursor() as cur:
        cur.execute("SELECT 1")
        result = cur.fetchone()
result

(1,)

In [71]:
with psycopg2.connect(PG_DSN) as conn:
     with conn.cursor() as cur:
         cur.execute(
             """
             INSER INTO public.customer(...)
             VALUES (%s, %s, %s)
             """
             ,
             row_for_db
         )
        conn.commit()

SyntaxError: incomplete input (493559432.py, line 4)

In [ ]:
with psycopg2.connect(PG_DSN) as conn:
     with conn.cursor() as cur:
         cur.executemanu(
             """
             INSER INTO public.customer(...)
             VALUES (%s, %s, %s)
             """
             ,
             row_for_db
         )
        conn.commit()

In [75]:
with (Path("data/orders.json")).open("r", encoding = "utf-8") as f:
    orders_data = json.load(f)

In [76]:
orders_data[0]

{'order_id': 10001,
 'cart_id': 1,
 'customer': {'user_id': 1, 'city': 'Chicago'},
 'status': 'CONFIRMED',
 'created_at': '2026-05-01T10:15:00Z',
 'channel': {'name': 'mobile_app',
  'utm': {'source': 'push', 'campaign': 'spring_sale'}},
 'payment': {'payment_id': 'pay_10001',
  'status': 'PAID',
  'amount': '352.38',
  'currency': 'USD',
  'attempts': [{'provider': 'stripe',
    'status': 'failed',
    'attempted_at': '2026-05-01T10:15:45Z',
    'error': {'code': 'insufficient_funds'}},
   {'provider': 'stripe',
    'status': 'success',
    'attempted_at': '2026-05-01T10:16:12Z',
    'error': None}]},
 'items': [{'line_no': 1,
   'product_id': 1,
   'sku': 'ESS-001',
   'quantity': '2',
   'unit_price': '129.99',
   'category_path': ['beauty', 'makeup'],
   'adjustments': [{'type': 'discount',
     'amount': '-10.00',
     'reason': 'campaign'},
    {'type': 'tax', 'amount': '12.00', 'reason': 'sales_tax'}]},
  {'line_no': 2,
   'product_id': 2,
   'sku': 'EYE-002',
   'quantity': '1',
   'unit_price': '99.90',
   'category_path': ['beauty', 'makeup'],
   'adjustments': []}]}

In [81]:
order_rows = []
for order in orders_data:
    order_rows.append(
            {
                "order_id": order["order_id"],
                "user_id": order["customer"]["user_id"],
                "city": order["customer"]["city"],
                "created_at": order["created_at"],
                "status": order["status"].lower()
            }
    )

In [82]:
orders_df = pd.DataFrame(order_rows)

In [83]:
orders_df

   order_id  user_id     city            created_at     status
0     10001        1  Chicago  2026-05-01T10:15:00Z  confirmed
1     10002        2  Houston  2026-05-02T12:00:00Z  confirmed

In [87]:
rows_to_insert = []

for row in orders_df.itertuples(index=False):
    rows_to_insert.append(
        (
            row.order_id,
            row.user_id,
            row.city,
            row.created_at,
            row.status
        )
    )

In [88]:
rows_to_insert

[(10001, 1, 'Chicago', '2026-05-01T10:15:00Z', 'confirmed'),
 (10002, 2, 'Houston', '2026-05-02T12:00:00Z', 'confirmed')]

In [89]:
with psycopg2.connect(PG_DSN) as conn:
    with conn.cursor() as cur:
        cur.execute(
            """
            CREATE SCHEMA stg IF NOT EXISTS;
            CREATE TABLE stg.orders(
                order_id BIGINT PRIMARY KEY,
                user_id BIGINT,
                city TEXT,
                created_at TIMESTAMPTZ,
                status TEXT
            )
            """
        )

In [90]:
conn.commit()

In [93]:
with psycopg2.connect(PG_DSN) as conn:
    with conn.cursor() as cur:
        cur.executemany(
            """
            INSERT INTO stg.orders(
                order_id,
                user_id,
                city,
                created_at,
                status
            )
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (order_id)
            DO UPDATE SET
                user_id = EXCLUDED.user_id,
                city = EXCLUDED.city,
                created_at = EXCLUDED.created_at,
                status = EXCLUDED.status
            """,
            rows_to_insert,
        )

In [94]:
conn.commit()

In [95]:
#requests
import requests

In [96]:
response = requests.get(
    "https://dummyjson.com/products",
    params={
        "limit":3,
        "skip":0
    },
    timeout = 10,
)

In [97]:
response.status_code

200

In [99]:
response.raise_for_status()

In [100]:
payload = response.json()

In [101]:
payload.keys()

dict_keys(['products', 'total', 'skip', 'limit'])

In [102]:
payload["products"][0]

{'id': 1,
 'title': 'Essence Mascara Lash Princess',
 'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
 'category': 'beauty',
 'price': 9.99,
 'discountPercentage': 10.48,
 'rating': 2.56,
 'stock': 99,
 'tags': ['beauty', 'mascara'],
 'brand': 'Essence',
 'sku': 'BEA-ESS-ESS-001',
 'weight': 4,
 'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
 'warrantyInformation': '1 week warranty',
 'shippingInformation': 'Ships in 3-5 business days',
 'availabilityStatus': 'In Stock',
 'reviews': [{'rating': 3,
   'comment': 'Would not recommend!',
   'date': '2025-04-30T09:41:02.053Z',
   'reviewerName': 'Eleanor Collins',
   'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
  {'rating': 4,
   'comment': 'Very satisfied!',
   'date': '2025-04-30T09:41:02.053Z',
   'reviewerName': 'Lucas Gordon',
   'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
  {'rating': 5,
   'comment': 'Highly impressed!',
   'date': '2025-04-30T09:41:02.053Z',
   'reviewerName': 'Eleanor Collins',
   'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
 'returnPolicy': 'No return policy',
 'minimumOrderQuantity': 48,
 'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
  'updatedAt': '2025-04-30T09:41:02.053Z',
  'barcode': '5784719087687',
  'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
 'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
 'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'}

In [103]:
df = pd.DataFrame(
    [
        {
            "product_id": product["id"],
            "price": product["price"],
            "stock": product["stock"],
        }
        for product in payload["products"]
    ]
)

In [104]:
df

   product_id  price  stock
0           1   9.99     99
1           2  19.99     34
2           3  14.99     89

In [3]:
import requests
products = []
limit = 30
skip = 0
max_rows = 60
while len(products) < max_rows:
    response = requests.get(
            "https://dummyjson.com/products",
                params={
                    "limit":limit,
                    "skip":skip,
                },
                timeout = 10,
    )
    response.raise_for_status()
    page = response.json()
    products.extend(page["products"])
    skip +=limit
    if skip >= page["total"]:
        break

In [5]:
products = products[:max_rows]

In [6]:
products

[{'id': 1,
  'title': 'Essence Mascara Lash Princess',
  'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
  'category': 'beauty',
  'price': 9.99,
  'discountPercentage': 10.48,
  'rating': 2.56,
  'stock': 99,
  'tags': ['beauty', 'mascara'],
  'brand': 'Essence',
  'sku': 'BEA-ESS-ESS-001',
  'weight': 4,
  'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships in 3-5 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 3,
    'comment': 'Would not recommend!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Very satisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Lucas Gordon',
    'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 48,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '5784719087687',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
 {'id': 2,
  'title': 'Eyeshadow Palette with Mirror',
  'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
  'category': 'beauty',
  'price': 19.99,
  'discountPercentage': 18.19,
  'rating': 2.86,
  'stock': 34,
  'tags': ['beauty', 'eyeshadow'],
  'brand': 'Glamour Beauty',
  'sku': 'BEA-GLA-EYE-002',
  'weight': 9,
  'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
  'warrantyInformation': '1 year warranty',
  'shippingInformation': 'Ships in 2 weeks',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Savannah Gomez',
    'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Awesome product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Christian Perez',
    'reviewerEmail': 'christian.perez@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nicholas Bailey',
    'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 20,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9170275171413',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'},
 {'id': 3,
  'title': 'Powder Canister',
  'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
  'category': 'beauty',
  'price': 14.99,
  'discountPercentage': 9.84,
  'rating': 4.64,
  'stock': 89,
  'tags': ['beauty', 'face powder'],
  'brand': 'Velvet Touch',
  'sku': 'BEA-VEL-POW-003',
  'weight': 8,
  'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59},
  'warrantyInformation': '3 months warranty',
  'shippingInformation': 'Ships in 1-2 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Alexander Jones',
    'reviewerEmail': 'alexander.jones@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Elijah Cruz',
    'reviewerEmail': 'elijah.cruz@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Very dissatisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Avery Perez',
    'reviewerEmail': 'avery.perez@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 22,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '8418883906837',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'},
 {'id': 4,
  'title': 'Red Lipstick',
  'description': 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
  'category': 'beauty',
  'price': 12.99,
  'discountPercentage': 12.16,
  'rating': 4.36,
  'stock': 91,
  'tags': ['beauty', 'lipstick'],
  'brand': 'Chic Cosmetics',
  'sku': 'BEA-CHI-LIP-004',
  'weight': 1,
  'dimensions': {'width': 18.11, 'height': 28.38, 'depth': 22.17},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships in 1 week',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Liam Garcia',
    'reviewerEmail': 'liam.garcia@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Ruby Andrews',
    'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Clara Berry',
    'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 40,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9467746727219',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'},
 {'id': 5,
  'title': 'Red Nail Polish',
  'description': 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
  'category': 'beauty',
  'price': 8.99,
  'discountPercentage': 11.44,
  'rating': 4.32,
  'stock': 79,
  'tags': ['beauty', 'nail polish'],
  'brand': 'Nail Couture',
  'sku': 'BEA-NAI-NAI-005',
  'weight': 8,
  'dimensions': {'width': 21.63, 'height': 16.48, 'depth': 29.84},
  'warrantyInformation': '1 month warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 2,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Benjamin Wilson',
    'reviewerEmail': 'benjamin.wilson@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Liam Smith',
    'reviewerEmail': 'liam.smith@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Very unhappy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Clara Berry',
    'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 22,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '4063010628104',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp'},
 {'id': 6,
  'title': 'Calvin Klein CK One',
  'description': "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
  'category': 'fragrances',
  'price': 49.99,
  'discountPercentage': 1.89,
  'rating': 4.37,
  'stock': 29,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Calvin Klein',
  'sku': 'FRA-CAL-CAL-006',
  'weight': 7,
  'dimensions': {'width': 29.36, 'height': 27.76, 'depth': 20.72},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 2,
    'comment': 'Very disappointed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Layla Young',
    'reviewerEmail': 'layla.young@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Fast shipping!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Daniel Cook',
    'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
   {'rating': 3,
    'comment': 'Not as described!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Jacob Cooper',
    'reviewerEmail': 'jacob.cooper@x.dummyjson.com'}],
  'returnPolicy': '90 days return policy',
  'minimumOrderQuantity': 9,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '2451534060749',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp'},
 {'id': 7,
  'title': 'Chanel Coco Noir Eau De',
  'description': 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
  'category': 'fragrances',
  'price': 129.99,
  'discountPercentage': 16.51,
  'rating': 4.26,
  'stock': 58,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Chanel',
  'sku': 'FRA-CHA-CHA-007',
  'weight': 7,
  'dimensions': {'width': 24.5, 'height': 25.7, 'depth': 25.98},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Ruby Andrews',
    'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Awesome product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Leah Henderson',
    'reviewerEmail': 'leah.henderson@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Very happy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Xavier Wright',
    'reviewerEmail': 'xavier.wright@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 1,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '4091737746820',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp'},
 {'id': 8,
  'title': "Dior J'adore",
  'description': "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
  'category': 'fragrances',
  'price': 89.99,
  'discountPercentage': 14.72,
  'rating': 3.8,
  'stock': 98,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Dior',
  'sku': 'FRA-DIO-DIO-008',
  'weight': 4,
  'dimensions': {'width': 27.67, 'height': 28.28, 'depth': 11.83},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships in 2 weeks',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 5,
    'comment': 'Great value for money!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nicholas Bailey',
    'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Great value for money!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Penelope Harper',
    'reviewerEmail': 'penelope.harper@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Emma Miller',
    'reviewerEmail': 'emma.miller@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 10,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '1445086097250',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ["https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
   "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp",
   "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp"],
  'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
 {'id': 9,
  'title': 'Dolce Shine Eau de',
  'description': "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
  'category': 'fragrances',
  'price': 69.99,
  'discountPercentage': 0.62,
  'rating': 3.96,
  'stock': 4,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Dolce & Gabbana',
  'sku': 'FRA-DOL-DOL-009',
  'weight': 6,
  'dimensions': {'width': 27.28, 'height': 29.88, 'depth': 18.3},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships in 1 month',
  'availabilityStatus': 'Low Stock',
  'reviews': [{'rating': 4,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Mateo Bennett',
    'reviewerEmail': 'mateo.bennett@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Highly recommended!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nolan Gonzalez',
    'reviewerEmail': 'nolan.gonzalez@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Very happy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Aurora Lawson',
    'reviewerEmail': 'aurora.lawson@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 2,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '3023868210708',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
 {'id': 10,
  'title': 'Gucci Bloom Eau de',
  'description': "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
  'category': 'fragrances',
  'price': 79.99,
  'discountPercentage': 14.39,
  'rating': 2.74,
  'stock': 91,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Gucci',
  'sku': 'FRA-GUC-GUC-010',
  'weight': 7,
  'dimensions': {'width': 20.92, 'height': 21.68, 'depth': 11.2},
  'warrantyInformation': '6 months warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 1,
    'comment': 'Very dissatisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Cameron Perez',
    'reviewerEmail': 'cameron.perez@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Very happy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Daniel Cook',
    'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Addison Wright',
    'reviewerEmail': 'addison.wright@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 2,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '3170832177880',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp'},
 {'id': 11,
  'title': 'Annibale Colombo Bed',
  'description': 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
  'category': 'furniture',
  'price': 1899.99,
  'discountPercentage': 8.57,
  'rating': 4.77,
  'stock': 88,
  'tags': ['furniture', 'beds'],
  'brand': 'Annibale Colombo',
  'sku': 'FUR-ANN-ANN-011',
  'weight': 10,
  'dimensions': {'width': 28.16, 'height': 25.36, 'depth': 17.28},
  'warrantyInformation': '1 year warranty',
  'shippingInformation': 'Ships in 1 month',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 2,
    'comment': 'Would not recommend!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Christopher West',
    'reviewerEmail': 'christopher.west@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Vivian Carter',
    'reviewerEmail': 'vivian.carter@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Mason Wright',
    'reviewerEmail': 'mason.wright@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 1,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '3610757456581',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp',
   'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp',
   'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
 {'id': 12,
  'title': 'Annibale Colombo Sofa',
  'description': 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
  'category': 'furniture',
  'price': 2499.99,
  'discountPercentage': 14.4,
  'rating': 3.92,
  'stock': 60,
  'tags': ['furniture', 'sofas'],
  'brand': 'Annibale Colombo',
  'sku': 'FUR-ANN-ANN-012',
  'weight': 6,
  'dimensions': {'width': 12.75, 'height': 20.55, 'depth': 19.06},
  'warrantyInformation': 'Lifetime warranty',
  'shippingInformation': 'Ships in 1 week',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 3,
    'comment': 'Very unhappy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',

In [7]:
len(products)

60